import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  entry: [
    'src/router.tsx',
    'src/providers.tsx',
    'src/routes/**/*.{ts,tsx}!',
    'src/env/*.ts',
    'run-jiti.js',
    'prisma/seed/*.ts',
    'src/features/build-info/script-to-generate-json.ts',
  ],
  project: ['src/**/*.{ts,tsx}', 'prisma/**/*.ts', 'e2e/**/*.ts'],
  paths: {
    'e2e/*': ['./e2e/*'],
  },
  ignore: [
    'src/routeTree.gen.ts', // auto-generated by TanStack Router
    'src/components/icons/generated/**', // auto-generated by svgr
    'src/server/db/generated/**', // auto-generated by Prisma
  ],
  ignoreDependencies: [
    'babel-plugin-react-compiler', // referenced as string in vite.config.ts babel plugins
    'dotenv-cli', // used via npm scripts
    'resize-observer-polyfill', // used in test setup
    'tailwindcss', // used via CSS @import
    'tw-animate-css', // used via CSS @import
    '@fontsource-variable/public-sans', // used via CSS @import
  ],
  storybook: {
    config: ['.storybook/main.ts'],
    entry: ['src/**/*.stories.{ts,tsx}', '.storybook/preview.tsx'],
  },
  playwright: {
    config: ['playwright.config.ts'],
    entry: ['e2e/**/*.spec.ts', 'e2e/global-setup.ts', 'e2e/setup/**/*.ts'],
  },
  vitest: {
    config: ['vitest.config.ts'],
    entry: [
      'src/**/*.unit.{test,spec}.?(c|m)[jt]s?(x)',
      'src/**/*.browser.{test,spec}.?(c|m)[jt]s?(x)',
    ],
  },
};

export default config;
