/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ManagerRouteRouteImport } from './routes/manager/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as InvitationsIdRouteImport } from './routes/invitations/$id'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ManagerUsersRouteRouteImport } from './routes/manager/users/route'
import { Route as ManagerOrganizationsRouteRouteImport } from './routes/manager/organizations/route'
import { Route as ManagerOrgSlugRouteRouteImport } from './routes/manager/$orgSlug/route'
import { Route as AppOrgSlugRouteRouteImport } from './routes/app/$orgSlug/route'
import { Route as ManagerUsersIndexRouteImport } from './routes/manager/users/index'
import { Route as ManagerOrganizationsIndexRouteImport } from './routes/manager/organizations/index'
import { Route as ManagerOrgSlugIndexRouteImport } from './routes/manager/$orgSlug/index'
import { Route as LoginVerifyIndexRouteImport } from './routes/login/verify.index'
import { Route as LoginErrorIndexRouteImport } from './routes/login/error.index'
import { Route as AppOrgSlugIndexRouteImport } from './routes/app/$orgSlug/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiRestSplatRouteImport } from './routes/api/rest.$'
import { Route as ApiOpenapiAuthRouteImport } from './routes/api/openapi/auth'
import { Route as ApiOpenapiAppRouteImport } from './routes/api/openapi/app'
import { Route as ApiCronDailyReminderRouteImport } from './routes/api/cron/daily-reminder'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ManagerUsersNewIndexRouteImport } from './routes/manager/users/new.index'
import { Route as ManagerUsersIdIndexRouteImport } from './routes/manager/users/$id.index'
import { Route as ManagerOrganizationsNewIndexRouteImport } from './routes/manager/organizations/new.index'
import { Route as ManagerOrgSlugUsersIndexRouteImport } from './routes/manager/$orgSlug/users/index'
import { Route as ManagerOrgSlugStatsIndexRouteImport } from './routes/manager/$orgSlug/stats.index'
import { Route as ManagerOrgSlugAccountIndexRouteImport } from './routes/manager/$orgSlug/account.index'
import { Route as AppOrgSlugRequestsIndexRouteImport } from './routes/app/$orgSlug/requests/index'
import { Route as AppOrgSlugCommutesIndexRouteImport } from './routes/app/$orgSlug/commutes/index'
import { Route as AppOrgSlugAccountIndexRouteImport } from './routes/app/$orgSlug/account/index'
import { Route as ApiOpenapiAuthSchemaRouteImport } from './routes/api/openapi/auth.schema'
import { Route as ApiOpenapiAppSchemaRouteImport } from './routes/api/openapi/app.schema'
import { Route as ApiDevSlackTemplateRouteImport } from './routes/api/dev.slack.$template'
import { Route as ApiDevEmailTemplateRouteImport } from './routes/api/dev.email.$template'
import { Route as ManagerUsersIdUpdateIndexRouteImport } from './routes/manager/users/$id.update.index'
import { Route as ManagerOrgSlugUsersNewIndexRouteImport } from './routes/manager/$orgSlug/users/new.index'
import { Route as ManagerOrgSlugUsersIdIndexRouteImport } from './routes/manager/$orgSlug/users/$id.index'
import { Route as AppOrgSlugCommutesRequestIndexRouteImport } from './routes/app/$orgSlug/commutes/request.index'
import { Route as AppOrgSlugCommutesNewIndexRouteImport } from './routes/app/$orgSlug/commutes/new.index'
import { Route as AppOrgSlugAccountLocationsIndexRouteImport } from './routes/app/$orgSlug/account/locations/index'
import { Route as AppOrgSlugAccountCommuteTemplatesIndexRouteImport } from './routes/app/$orgSlug/account/commute-templates/index'
import { Route as ManagerOrgSlugUsersIdUpdateIndexRouteImport } from './routes/manager/$orgSlug/users/$id.update.index'
import { Route as AppOrgSlugCommutesIdUpdateIndexRouteImport } from './routes/app/$orgSlug/commutes/$id.update.index'
import { Route as AppOrgSlugAccountCommuteTemplatesNewIndexRouteImport } from './routes/app/$orgSlug/account/commute-templates/new.index'
import { Route as AppOrgSlugAccountCommuteTemplatesIdUpdateIndexRouteImport } from './routes/app/$orgSlug/account/commute-templates/$id.update.index'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRouteRoute = ManagerRouteRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const InvitationsIdRoute = InvitationsIdRouteImport.update({
  id: '/invitations/$id',
  path: '/invitations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerUsersRouteRoute = ManagerUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerOrganizationsRouteRoute =
  ManagerOrganizationsRouteRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => ManagerRouteRoute,
  } as any)
const ManagerOrgSlugRouteRoute = ManagerOrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const AppOrgSlugRouteRoute = AppOrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AppRouteRoute,
} as any)
const ManagerUsersIndexRoute = ManagerUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerUsersRouteRoute,
} as any)
const ManagerOrganizationsIndexRoute =
  ManagerOrganizationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ManagerOrganizationsRouteRoute,
  } as any)
const ManagerOrgSlugIndexRoute = ManagerOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerOrgSlugRouteRoute,
} as any)
const LoginVerifyIndexRoute = LoginVerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const LoginErrorIndexRoute = LoginErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppOrgSlugIndexRoute = AppOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestSplatRoute = ApiRestSplatRouteImport.update({
  id: '/api/rest/$',
  path: '/api/rest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiAuthRoute = ApiOpenapiAuthRouteImport.update({
  id: '/api/openapi/auth',
  path: '/api/openapi/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiAppRoute = ApiOpenapiAppRouteImport.update({
  id: '/api/openapi/app',
  path: '/api/openapi/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDailyReminderRoute = ApiCronDailyReminderRouteImport.update({
  id: '/api/cron/daily-reminder',
  path: '/api/cron/daily-reminder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerUsersNewIndexRoute = ManagerUsersNewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => ManagerUsersRouteRoute,
} as any)
const ManagerUsersIdIndexRoute = ManagerUsersIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => ManagerUsersRouteRoute,
} as any)
const ManagerOrganizationsNewIndexRoute =
  ManagerOrganizationsNewIndexRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => ManagerOrganizationsRouteRoute,
  } as any)
const ManagerOrgSlugUsersIndexRoute =
  ManagerOrgSlugUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => ManagerOrgSlugRouteRoute,
  } as any)
const ManagerOrgSlugStatsIndexRoute =
  ManagerOrgSlugStatsIndexRouteImport.update({
    id: '/stats/',
    path: '/stats/',
    getParentRoute: () => ManagerOrgSlugRouteRoute,
  } as any)
const ManagerOrgSlugAccountIndexRoute =
  ManagerOrgSlugAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => ManagerOrgSlugRouteRoute,
  } as any)
const AppOrgSlugRequestsIndexRoute = AppOrgSlugRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugCommutesIndexRoute = AppOrgSlugCommutesIndexRouteImport.update({
  id: '/commutes/',
  path: '/commutes/',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugAccountIndexRoute = AppOrgSlugAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const ApiOpenapiAuthSchemaRoute = ApiOpenapiAuthSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => ApiOpenapiAuthRoute,
} as any)
const ApiOpenapiAppSchemaRoute = ApiOpenapiAppSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => ApiOpenapiAppRoute,
} as any)
const ApiDevSlackTemplateRoute = ApiDevSlackTemplateRouteImport.update({
  id: '/api/dev/slack/$template',
  path: '/api/dev/slack/$template',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevEmailTemplateRoute = ApiDevEmailTemplateRouteImport.update({
  id: '/api/dev/email/$template',
  path: '/api/dev/email/$template',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerUsersIdUpdateIndexRoute =
  ManagerUsersIdUpdateIndexRouteImport.update({
    id: '/$id/update/',
    path: '/$id/update/',
    getParentRoute: () => ManagerUsersRouteRoute,
  } as any)
const ManagerOrgSlugUsersNewIndexRoute =
  ManagerOrgSlugUsersNewIndexRouteImport.update({
    id: '/users/new/',
    path: '/users/new/',
    getParentRoute: () => ManagerOrgSlugRouteRoute,
  } as any)
const ManagerOrgSlugUsersIdIndexRoute =
  ManagerOrgSlugUsersIdIndexRouteImport.update({
    id: '/users/$id/',
    path: '/users/$id/',
    getParentRoute: () => ManagerOrgSlugRouteRoute,
  } as any)
const AppOrgSlugCommutesRequestIndexRoute =
  AppOrgSlugCommutesRequestIndexRouteImport.update({
    id: '/commutes/request/',
    path: '/commutes/request/',
    getParentRoute: () => AppOrgSlugRouteRoute,
  } as any)
const AppOrgSlugCommutesNewIndexRoute =
  AppOrgSlugCommutesNewIndexRouteImport.update({
    id: '/commutes/new/',
    path: '/commutes/new/',
    getParentRoute: () => AppOrgSlugRouteRoute,
  } as any)
const AppOrgSlugAccountLocationsIndexRoute =
  AppOrgSlugAccountLocationsIndexRouteImport.update({
    id: '/account/locations/',
    path: '/account/locations/',
    getParentRoute: () => AppOrgSlugRouteRoute,
  } as any)
const AppOrgSlugAccountCommuteTemplatesIndexRoute =
  AppOrgSlugAccountCommuteTemplatesIndexRouteImport.update({
    id: '/account/commute-templates/',
    path: '/account/commute-templates/',
    getParentRoute: () => AppOrgSlugRouteRoute,
  } as any)
const ManagerOrgSlugUsersIdUpdateIndexRoute =
  ManagerOrgSlugUsersIdUpdateIndexRouteImport.update({
    id: '/users/$id/update/',
    path: '/users/$id/update/',
    getParentRoute: () => ManagerOrgSlugRouteRoute,
  } as any)
const AppOrgSlugCommutesIdUpdateIndexRoute =
  AppOrgSlugCommutesIdUpdateIndexRouteImport.update({
    id: '/commutes/$id/update/',
    path: '/commutes/$id/update/',
    getParentRoute: () => AppOrgSlugRouteRoute,
  } as any)
const AppOrgSlugAccountCommuteTemplatesNewIndexRoute =
  AppOrgSlugAccountCommuteTemplatesNewIndexRouteImport.update({
    id: '/account/commute-templates/new/',
    path: '/account/commute-templates/new/',
    getParentRoute: () => AppOrgSlugRouteRoute,
  } as any)
const AppOrgSlugAccountCommuteTemplatesIdUpdateIndexRoute =
  AppOrgSlugAccountCommuteTemplatesIdUpdateIndexRouteImport.update({
    id: '/account/commute-templates/$id/update/',
    path: '/account/commute-templates/$id/update/',
    getParentRoute: () => AppOrgSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/app/$orgSlug': typeof AppOrgSlugRouteRouteWithChildren
  '/manager/$orgSlug': typeof ManagerOrgSlugRouteRouteWithChildren
  '/manager/organizations': typeof ManagerOrganizationsRouteRouteWithChildren
  '/manager/users': typeof ManagerUsersRouteRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/invitations/$id': typeof InvitationsIdRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/daily-reminder': typeof ApiCronDailyReminderRoute
  '/api/openapi/app': typeof ApiOpenapiAppRouteWithChildren
  '/api/openapi/auth': typeof ApiOpenapiAuthRouteWithChildren
  '/api/rest/$': typeof ApiRestSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/$orgSlug/': typeof AppOrgSlugIndexRoute
  '/login/error/': typeof LoginErrorIndexRoute
  '/login/verify/': typeof LoginVerifyIndexRoute
  '/manager/$orgSlug/': typeof ManagerOrgSlugIndexRoute
  '/manager/organizations/': typeof ManagerOrganizationsIndexRoute
  '/manager/users/': typeof ManagerUsersIndexRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/dev/slack/$template': typeof ApiDevSlackTemplateRoute
  '/api/openapi/app/schema': typeof ApiOpenapiAppSchemaRoute
  '/api/openapi/auth/schema': typeof ApiOpenapiAuthSchemaRoute
  '/app/$orgSlug/account/': typeof AppOrgSlugAccountIndexRoute
  '/app/$orgSlug/commutes/': typeof AppOrgSlugCommutesIndexRoute
  '/app/$orgSlug/requests/': typeof AppOrgSlugRequestsIndexRoute
  '/manager/$orgSlug/account/': typeof ManagerOrgSlugAccountIndexRoute
  '/manager/$orgSlug/stats/': typeof ManagerOrgSlugStatsIndexRoute
  '/manager/$orgSlug/users/': typeof ManagerOrgSlugUsersIndexRoute
  '/manager/organizations/new/': typeof ManagerOrganizationsNewIndexRoute
  '/manager/users/$id/': typeof ManagerUsersIdIndexRoute
  '/manager/users/new/': typeof ManagerUsersNewIndexRoute
  '/app/$orgSlug/account/commute-templates/': typeof AppOrgSlugAccountCommuteTemplatesIndexRoute
  '/app/$orgSlug/account/locations/': typeof AppOrgSlugAccountLocationsIndexRoute
  '/app/$orgSlug/commutes/new/': typeof AppOrgSlugCommutesNewIndexRoute
  '/app/$orgSlug/commutes/request/': typeof AppOrgSlugCommutesRequestIndexRoute
  '/manager/$orgSlug/users/$id/': typeof ManagerOrgSlugUsersIdIndexRoute
  '/manager/$orgSlug/users/new/': typeof ManagerOrgSlugUsersNewIndexRoute
  '/manager/users/$id/update/': typeof ManagerUsersIdUpdateIndexRoute
  '/app/$orgSlug/account/commute-templates/new/': typeof AppOrgSlugAccountCommuteTemplatesNewIndexRoute
  '/app/$orgSlug/commutes/$id/update/': typeof AppOrgSlugCommutesIdUpdateIndexRoute
  '/manager/$orgSlug/users/$id/update/': typeof ManagerOrgSlugUsersIdUpdateIndexRoute
  '/app/$orgSlug/account/commute-templates/$id/update/': typeof AppOrgSlugAccountCommuteTemplatesIdUpdateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/api/upload': typeof ApiUploadRoute
  '/invitations/$id': typeof InvitationsIdRoute
  '/app': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/daily-reminder': typeof ApiCronDailyReminderRoute
  '/api/openapi/app': typeof ApiOpenapiAppRouteWithChildren
  '/api/openapi/auth': typeof ApiOpenapiAuthRouteWithChildren
  '/api/rest/$': typeof ApiRestSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/$orgSlug': typeof AppOrgSlugIndexRoute
  '/login/error': typeof LoginErrorIndexRoute
  '/login/verify': typeof LoginVerifyIndexRoute
  '/manager/$orgSlug': typeof ManagerOrgSlugIndexRoute
  '/manager/organizations': typeof ManagerOrganizationsIndexRoute
  '/manager/users': typeof ManagerUsersIndexRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/dev/slack/$template': typeof ApiDevSlackTemplateRoute
  '/api/openapi/app/schema': typeof ApiOpenapiAppSchemaRoute
  '/api/openapi/auth/schema': typeof ApiOpenapiAuthSchemaRoute
  '/app/$orgSlug/account': typeof AppOrgSlugAccountIndexRoute
  '/app/$orgSlug/commutes': typeof AppOrgSlugCommutesIndexRoute
  '/app/$orgSlug/requests': typeof AppOrgSlugRequestsIndexRoute
  '/manager/$orgSlug/account': typeof ManagerOrgSlugAccountIndexRoute
  '/manager/$orgSlug/stats': typeof ManagerOrgSlugStatsIndexRoute
  '/manager/$orgSlug/users': typeof ManagerOrgSlugUsersIndexRoute
  '/manager/organizations/new': typeof ManagerOrganizationsNewIndexRoute
  '/manager/users/$id': typeof ManagerUsersIdIndexRoute
  '/manager/users/new': typeof ManagerUsersNewIndexRoute
  '/app/$orgSlug/account/commute-templates': typeof AppOrgSlugAccountCommuteTemplatesIndexRoute
  '/app/$orgSlug/account/locations': typeof AppOrgSlugAccountLocationsIndexRoute
  '/app/$orgSlug/commutes/new': typeof AppOrgSlugCommutesNewIndexRoute
  '/app/$orgSlug/commutes/request': typeof AppOrgSlugCommutesRequestIndexRoute
  '/manager/$orgSlug/users/$id': typeof ManagerOrgSlugUsersIdIndexRoute
  '/manager/$orgSlug/users/new': typeof ManagerOrgSlugUsersNewIndexRoute
  '/manager/users/$id/update': typeof ManagerUsersIdUpdateIndexRoute
  '/app/$orgSlug/account/commute-templates/new': typeof AppOrgSlugAccountCommuteTemplatesNewIndexRoute
  '/app/$orgSlug/commutes/$id/update': typeof AppOrgSlugCommutesIdUpdateIndexRoute
  '/manager/$orgSlug/users/$id/update': typeof ManagerOrgSlugUsersIdUpdateIndexRoute
  '/app/$orgSlug/account/commute-templates/$id/update': typeof AppOrgSlugAccountCommuteTemplatesIdUpdateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/app/$orgSlug': typeof AppOrgSlugRouteRouteWithChildren
  '/manager/$orgSlug': typeof ManagerOrgSlugRouteRouteWithChildren
  '/manager/organizations': typeof ManagerOrganizationsRouteRouteWithChildren
  '/manager/users': typeof ManagerUsersRouteRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/invitations/$id': typeof InvitationsIdRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/daily-reminder': typeof ApiCronDailyReminderRoute
  '/api/openapi/app': typeof ApiOpenapiAppRouteWithChildren
  '/api/openapi/auth': typeof ApiOpenapiAuthRouteWithChildren
  '/api/rest/$': typeof ApiRestSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/$orgSlug/': typeof AppOrgSlugIndexRoute
  '/login/error/': typeof LoginErrorIndexRoute
  '/login/verify/': typeof LoginVerifyIndexRoute
  '/manager/$orgSlug/': typeof ManagerOrgSlugIndexRoute
  '/manager/organizations/': typeof ManagerOrganizationsIndexRoute
  '/manager/users/': typeof ManagerUsersIndexRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/dev/slack/$template': typeof ApiDevSlackTemplateRoute
  '/api/openapi/app/schema': typeof ApiOpenapiAppSchemaRoute
  '/api/openapi/auth/schema': typeof ApiOpenapiAuthSchemaRoute
  '/app/$orgSlug/account/': typeof AppOrgSlugAccountIndexRoute
  '/app/$orgSlug/commutes/': typeof AppOrgSlugCommutesIndexRoute
  '/app/$orgSlug/requests/': typeof AppOrgSlugRequestsIndexRoute
  '/manager/$orgSlug/account/': typeof ManagerOrgSlugAccountIndexRoute
  '/manager/$orgSlug/stats/': typeof ManagerOrgSlugStatsIndexRoute
  '/manager/$orgSlug/users/': typeof ManagerOrgSlugUsersIndexRoute
  '/manager/organizations/new/': typeof ManagerOrganizationsNewIndexRoute
  '/manager/users/$id/': typeof ManagerUsersIdIndexRoute
  '/manager/users/new/': typeof ManagerUsersNewIndexRoute
  '/app/$orgSlug/account/commute-templates/': typeof AppOrgSlugAccountCommuteTemplatesIndexRoute
  '/app/$orgSlug/account/locations/': typeof AppOrgSlugAccountLocationsIndexRoute
  '/app/$orgSlug/commutes/new/': typeof AppOrgSlugCommutesNewIndexRoute
  '/app/$orgSlug/commutes/request/': typeof AppOrgSlugCommutesRequestIndexRoute
  '/manager/$orgSlug/users/$id/': typeof ManagerOrgSlugUsersIdIndexRoute
  '/manager/$orgSlug/users/new/': typeof ManagerOrgSlugUsersNewIndexRoute
  '/manager/users/$id/update/': typeof ManagerUsersIdUpdateIndexRoute
  '/app/$orgSlug/account/commute-templates/new/': typeof AppOrgSlugAccountCommuteTemplatesNewIndexRoute
  '/app/$orgSlug/commutes/$id/update/': typeof AppOrgSlugCommutesIdUpdateIndexRoute
  '/manager/$orgSlug/users/$id/update/': typeof ManagerOrgSlugUsersIdUpdateIndexRoute
  '/app/$orgSlug/account/commute-templates/$id/update/': typeof AppOrgSlugAccountCommuteTemplatesIdUpdateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/manager'
    | '/logout'
    | '/app/$orgSlug'
    | '/manager/$orgSlug'
    | '/manager/organizations'
    | '/manager/users'
    | '/api/upload'
    | '/invitations/$id'
    | '/app/'
    | '/login/'
    | '/manager/'
    | '/api/auth/$'
    | '/api/cron/daily-reminder'
    | '/api/openapi/app'
    | '/api/openapi/auth'
    | '/api/rest/$'
    | '/api/rpc/$'
    | '/app/$orgSlug/'
    | '/login/error/'
    | '/login/verify/'
    | '/manager/$orgSlug/'
    | '/manager/organizations/'
    | '/manager/users/'
    | '/api/dev/email/$template'
    | '/api/dev/slack/$template'
    | '/api/openapi/app/schema'
    | '/api/openapi/auth/schema'
    | '/app/$orgSlug/account/'
    | '/app/$orgSlug/commutes/'
    | '/app/$orgSlug/requests/'
    | '/manager/$orgSlug/account/'
    | '/manager/$orgSlug/stats/'
    | '/manager/$orgSlug/users/'
    | '/manager/organizations/new/'
    | '/manager/users/$id/'
    | '/manager/users/new/'
    | '/app/$orgSlug/account/commute-templates/'
    | '/app/$orgSlug/account/locations/'
    | '/app/$orgSlug/commutes/new/'
    | '/app/$orgSlug/commutes/request/'
    | '/manager/$orgSlug/users/$id/'
    | '/manager/$orgSlug/users/new/'
    | '/manager/users/$id/update/'
    | '/app/$orgSlug/account/commute-templates/new/'
    | '/app/$orgSlug/commutes/$id/update/'
    | '/manager/$orgSlug/users/$id/update/'
    | '/app/$orgSlug/account/commute-templates/$id/update/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/api/upload'
    | '/invitations/$id'
    | '/app'
    | '/login'
    | '/manager'
    | '/api/auth/$'
    | '/api/cron/daily-reminder'
    | '/api/openapi/app'
    | '/api/openapi/auth'
    | '/api/rest/$'
    | '/api/rpc/$'
    | '/app/$orgSlug'
    | '/login/error'
    | '/login/verify'
    | '/manager/$orgSlug'
    | '/manager/organizations'
    | '/manager/users'
    | '/api/dev/email/$template'
    | '/api/dev/slack/$template'
    | '/api/openapi/app/schema'
    | '/api/openapi/auth/schema'
    | '/app/$orgSlug/account'
    | '/app/$orgSlug/commutes'
    | '/app/$orgSlug/requests'
    | '/manager/$orgSlug/account'
    | '/manager/$orgSlug/stats'
    | '/manager/$orgSlug/users'
    | '/manager/organizations/new'
    | '/manager/users/$id'
    | '/manager/users/new'
    | '/app/$orgSlug/account/commute-templates'
    | '/app/$orgSlug/account/locations'
    | '/app/$orgSlug/commutes/new'
    | '/app/$orgSlug/commutes/request'
    | '/manager/$orgSlug/users/$id'
    | '/manager/$orgSlug/users/new'
    | '/manager/users/$id/update'
    | '/app/$orgSlug/account/commute-templates/new'
    | '/app/$orgSlug/commutes/$id/update'
    | '/manager/$orgSlug/users/$id/update'
    | '/app/$orgSlug/account/commute-templates/$id/update'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/manager'
    | '/logout'
    | '/app/$orgSlug'
    | '/manager/$orgSlug'
    | '/manager/organizations'
    | '/manager/users'
    | '/api/upload'
    | '/invitations/$id'
    | '/app/'
    | '/login/'
    | '/manager/'
    | '/api/auth/$'
    | '/api/cron/daily-reminder'
    | '/api/openapi/app'
    | '/api/openapi/auth'
    | '/api/rest/$'
    | '/api/rpc/$'
    | '/app/$orgSlug/'
    | '/login/error/'
    | '/login/verify/'
    | '/manager/$orgSlug/'
    | '/manager/organizations/'
    | '/manager/users/'
    | '/api/dev/email/$template'
    | '/api/dev/slack/$template'
    | '/api/openapi/app/schema'
    | '/api/openapi/auth/schema'
    | '/app/$orgSlug/account/'
    | '/app/$orgSlug/commutes/'
    | '/app/$orgSlug/requests/'
    | '/manager/$orgSlug/account/'
    | '/manager/$orgSlug/stats/'
    | '/manager/$orgSlug/users/'
    | '/manager/organizations/new/'
    | '/manager/users/$id/'
    | '/manager/users/new/'
    | '/app/$orgSlug/account/commute-templates/'
    | '/app/$orgSlug/account/locations/'
    | '/app/$orgSlug/commutes/new/'
    | '/app/$orgSlug/commutes/request/'
    | '/manager/$orgSlug/users/$id/'
    | '/manager/$orgSlug/users/new/'
    | '/manager/users/$id/update/'
    | '/app/$orgSlug/account/commute-templates/new/'
    | '/app/$orgSlug/commutes/$id/update/'
    | '/manager/$orgSlug/users/$id/update/'
    | '/app/$orgSlug/account/commute-templates/$id/update/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  ManagerRouteRoute: typeof ManagerRouteRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  ApiUploadRoute: typeof ApiUploadRoute
  InvitationsIdRoute: typeof InvitationsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronDailyReminderRoute: typeof ApiCronDailyReminderRoute
  ApiOpenapiAppRoute: typeof ApiOpenapiAppRouteWithChildren
  ApiOpenapiAuthRoute: typeof ApiOpenapiAuthRouteWithChildren
  ApiRestSplatRoute: typeof ApiRestSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiDevEmailTemplateRoute: typeof ApiDevEmailTemplateRoute
  ApiDevSlackTemplateRoute: typeof ApiDevSlackTemplateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/invitations/$id': {
      id: '/invitations/$id'
      path: '/invitations/$id'
      fullPath: '/invitations/$id'
      preLoaderRoute: typeof InvitationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/users': {
      id: '/manager/users'
      path: '/users'
      fullPath: '/manager/users'
      preLoaderRoute: typeof ManagerUsersRouteRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/organizations': {
      id: '/manager/organizations'
      path: '/organizations'
      fullPath: '/manager/organizations'
      preLoaderRoute: typeof ManagerOrganizationsRouteRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/$orgSlug': {
      id: '/manager/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/manager/$orgSlug'
      preLoaderRoute: typeof ManagerOrgSlugRouteRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/app/$orgSlug': {
      id: '/app/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/app/$orgSlug'
      preLoaderRoute: typeof AppOrgSlugRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/manager/users/': {
      id: '/manager/users/'
      path: '/'
      fullPath: '/manager/users/'
      preLoaderRoute: typeof ManagerUsersIndexRouteImport
      parentRoute: typeof ManagerUsersRouteRoute
    }
    '/manager/organizations/': {
      id: '/manager/organizations/'
      path: '/'
      fullPath: '/manager/organizations/'
      preLoaderRoute: typeof ManagerOrganizationsIndexRouteImport
      parentRoute: typeof ManagerOrganizationsRouteRoute
    }
    '/manager/$orgSlug/': {
      id: '/manager/$orgSlug/'
      path: '/'
      fullPath: '/manager/$orgSlug/'
      preLoaderRoute: typeof ManagerOrgSlugIndexRouteImport
      parentRoute: typeof ManagerOrgSlugRouteRoute
    }
    '/login/verify/': {
      id: '/login/verify/'
      path: '/verify'
      fullPath: '/login/verify/'
      preLoaderRoute: typeof LoginVerifyIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/login/error/': {
      id: '/login/error/'
      path: '/error'
      fullPath: '/login/error/'
      preLoaderRoute: typeof LoginErrorIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/app/$orgSlug/': {
      id: '/app/$orgSlug/'
      path: '/'
      fullPath: '/app/$orgSlug/'
      preLoaderRoute: typeof AppOrgSlugIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rest/$': {
      id: '/api/rest/$'
      path: '/api/rest/$'
      fullPath: '/api/rest/$'
      preLoaderRoute: typeof ApiRestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/auth': {
      id: '/api/openapi/auth'
      path: '/api/openapi/auth'
      fullPath: '/api/openapi/auth'
      preLoaderRoute: typeof ApiOpenapiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/app': {
      id: '/api/openapi/app'
      path: '/api/openapi/app'
      fullPath: '/api/openapi/app'
      preLoaderRoute: typeof ApiOpenapiAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/daily-reminder': {
      id: '/api/cron/daily-reminder'
      path: '/api/cron/daily-reminder'
      fullPath: '/api/cron/daily-reminder'
      preLoaderRoute: typeof ApiCronDailyReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/users/new/': {
      id: '/manager/users/new/'
      path: '/new'
      fullPath: '/manager/users/new/'
      preLoaderRoute: typeof ManagerUsersNewIndexRouteImport
      parentRoute: typeof ManagerUsersRouteRoute
    }
    '/manager/users/$id/': {
      id: '/manager/users/$id/'
      path: '/$id'
      fullPath: '/manager/users/$id/'
      preLoaderRoute: typeof ManagerUsersIdIndexRouteImport
      parentRoute: typeof ManagerUsersRouteRoute
    }
    '/manager/organizations/new/': {
      id: '/manager/organizations/new/'
      path: '/new'
      fullPath: '/manager/organizations/new/'
      preLoaderRoute: typeof ManagerOrganizationsNewIndexRouteImport
      parentRoute: typeof ManagerOrganizationsRouteRoute
    }
    '/manager/$orgSlug/users/': {
      id: '/manager/$orgSlug/users/'
      path: '/users'
      fullPath: '/manager/$orgSlug/users/'
      preLoaderRoute: typeof ManagerOrgSlugUsersIndexRouteImport
      parentRoute: typeof ManagerOrgSlugRouteRoute
    }
    '/manager/$orgSlug/stats/': {
      id: '/manager/$orgSlug/stats/'
      path: '/stats'
      fullPath: '/manager/$orgSlug/stats/'
      preLoaderRoute: typeof ManagerOrgSlugStatsIndexRouteImport
      parentRoute: typeof ManagerOrgSlugRouteRoute
    }
    '/manager/$orgSlug/account/': {
      id: '/manager/$orgSlug/account/'
      path: '/account'
      fullPath: '/manager/$orgSlug/account/'
      preLoaderRoute: typeof ManagerOrgSlugAccountIndexRouteImport
      parentRoute: typeof ManagerOrgSlugRouteRoute
    }
    '/app/$orgSlug/requests/': {
      id: '/app/$orgSlug/requests/'
      path: '/requests'
      fullPath: '/app/$orgSlug/requests/'
      preLoaderRoute: typeof AppOrgSlugRequestsIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/commutes/': {
      id: '/app/$orgSlug/commutes/'
      path: '/commutes'
      fullPath: '/app/$orgSlug/commutes/'
      preLoaderRoute: typeof AppOrgSlugCommutesIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/account/': {
      id: '/app/$orgSlug/account/'
      path: '/account'
      fullPath: '/app/$orgSlug/account/'
      preLoaderRoute: typeof AppOrgSlugAccountIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/api/openapi/auth/schema': {
      id: '/api/openapi/auth/schema'
      path: '/schema'
      fullPath: '/api/openapi/auth/schema'
      preLoaderRoute: typeof ApiOpenapiAuthSchemaRouteImport
      parentRoute: typeof ApiOpenapiAuthRoute
    }
    '/api/openapi/app/schema': {
      id: '/api/openapi/app/schema'
      path: '/schema'
      fullPath: '/api/openapi/app/schema'
      preLoaderRoute: typeof ApiOpenapiAppSchemaRouteImport
      parentRoute: typeof ApiOpenapiAppRoute
    }
    '/api/dev/slack/$template': {
      id: '/api/dev/slack/$template'
      path: '/api/dev/slack/$template'
      fullPath: '/api/dev/slack/$template'
      preLoaderRoute: typeof ApiDevSlackTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/email/$template': {
      id: '/api/dev/email/$template'
      path: '/api/dev/email/$template'
      fullPath: '/api/dev/email/$template'
      preLoaderRoute: typeof ApiDevEmailTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/users/$id/update/': {
      id: '/manager/users/$id/update/'
      path: '/$id/update'
      fullPath: '/manager/users/$id/update/'
      preLoaderRoute: typeof ManagerUsersIdUpdateIndexRouteImport
      parentRoute: typeof ManagerUsersRouteRoute
    }
    '/manager/$orgSlug/users/new/': {
      id: '/manager/$orgSlug/users/new/'
      path: '/users/new'
      fullPath: '/manager/$orgSlug/users/new/'
      preLoaderRoute: typeof ManagerOrgSlugUsersNewIndexRouteImport
      parentRoute: typeof ManagerOrgSlugRouteRoute
    }
    '/manager/$orgSlug/users/$id/': {
      id: '/manager/$orgSlug/users/$id/'
      path: '/users/$id'
      fullPath: '/manager/$orgSlug/users/$id/'
      preLoaderRoute: typeof ManagerOrgSlugUsersIdIndexRouteImport
      parentRoute: typeof ManagerOrgSlugRouteRoute
    }
    '/app/$orgSlug/commutes/request/': {
      id: '/app/$orgSlug/commutes/request/'
      path: '/commutes/request'
      fullPath: '/app/$orgSlug/commutes/request/'
      preLoaderRoute: typeof AppOrgSlugCommutesRequestIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/commutes/new/': {
      id: '/app/$orgSlug/commutes/new/'
      path: '/commutes/new'
      fullPath: '/app/$orgSlug/commutes/new/'
      preLoaderRoute: typeof AppOrgSlugCommutesNewIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/account/locations/': {
      id: '/app/$orgSlug/account/locations/'
      path: '/account/locations'
      fullPath: '/app/$orgSlug/account/locations/'
      preLoaderRoute: typeof AppOrgSlugAccountLocationsIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/account/commute-templates/': {
      id: '/app/$orgSlug/account/commute-templates/'
      path: '/account/commute-templates'
      fullPath: '/app/$orgSlug/account/commute-templates/'
      preLoaderRoute: typeof AppOrgSlugAccountCommuteTemplatesIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/manager/$orgSlug/users/$id/update/': {
      id: '/manager/$orgSlug/users/$id/update/'
      path: '/users/$id/update'
      fullPath: '/manager/$orgSlug/users/$id/update/'
      preLoaderRoute: typeof ManagerOrgSlugUsersIdUpdateIndexRouteImport
      parentRoute: typeof ManagerOrgSlugRouteRoute
    }
    '/app/$orgSlug/commutes/$id/update/': {
      id: '/app/$orgSlug/commutes/$id/update/'
      path: '/commutes/$id/update'
      fullPath: '/app/$orgSlug/commutes/$id/update/'
      preLoaderRoute: typeof AppOrgSlugCommutesIdUpdateIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/account/commute-templates/new/': {
      id: '/app/$orgSlug/account/commute-templates/new/'
      path: '/account/commute-templates/new'
      fullPath: '/app/$orgSlug/account/commute-templates/new/'
      preLoaderRoute: typeof AppOrgSlugAccountCommuteTemplatesNewIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/account/commute-templates/$id/update/': {
      id: '/app/$orgSlug/account/commute-templates/$id/update/'
      path: '/account/commute-templates/$id/update'
      fullPath: '/app/$orgSlug/account/commute-templates/$id/update/'
      preLoaderRoute: typeof AppOrgSlugAccountCommuteTemplatesIdUpdateIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
  }
}

interface AppOrgSlugRouteRouteChildren {
  AppOrgSlugIndexRoute: typeof AppOrgSlugIndexRoute
  AppOrgSlugAccountIndexRoute: typeof AppOrgSlugAccountIndexRoute
  AppOrgSlugCommutesIndexRoute: typeof AppOrgSlugCommutesIndexRoute
  AppOrgSlugRequestsIndexRoute: typeof AppOrgSlugRequestsIndexRoute
  AppOrgSlugAccountCommuteTemplatesIndexRoute: typeof AppOrgSlugAccountCommuteTemplatesIndexRoute
  AppOrgSlugAccountLocationsIndexRoute: typeof AppOrgSlugAccountLocationsIndexRoute
  AppOrgSlugCommutesNewIndexRoute: typeof AppOrgSlugCommutesNewIndexRoute
  AppOrgSlugCommutesRequestIndexRoute: typeof AppOrgSlugCommutesRequestIndexRoute
  AppOrgSlugAccountCommuteTemplatesNewIndexRoute: typeof AppOrgSlugAccountCommuteTemplatesNewIndexRoute
  AppOrgSlugCommutesIdUpdateIndexRoute: typeof AppOrgSlugCommutesIdUpdateIndexRoute
  AppOrgSlugAccountCommuteTemplatesIdUpdateIndexRoute: typeof AppOrgSlugAccountCommuteTemplatesIdUpdateIndexRoute
}

const AppOrgSlugRouteRouteChildren: AppOrgSlugRouteRouteChildren = {
  AppOrgSlugIndexRoute: AppOrgSlugIndexRoute,
  AppOrgSlugAccountIndexRoute: AppOrgSlugAccountIndexRoute,
  AppOrgSlugCommutesIndexRoute: AppOrgSlugCommutesIndexRoute,
  AppOrgSlugRequestsIndexRoute: AppOrgSlugRequestsIndexRoute,
  AppOrgSlugAccountCommuteTemplatesIndexRoute:
    AppOrgSlugAccountCommuteTemplatesIndexRoute,
  AppOrgSlugAccountLocationsIndexRoute: AppOrgSlugAccountLocationsIndexRoute,
  AppOrgSlugCommutesNewIndexRoute: AppOrgSlugCommutesNewIndexRoute,
  AppOrgSlugCommutesRequestIndexRoute: AppOrgSlugCommutesRequestIndexRoute,
  AppOrgSlugAccountCommuteTemplatesNewIndexRoute:
    AppOrgSlugAccountCommuteTemplatesNewIndexRoute,
  AppOrgSlugCommutesIdUpdateIndexRoute: AppOrgSlugCommutesIdUpdateIndexRoute,
  AppOrgSlugAccountCommuteTemplatesIdUpdateIndexRoute:
    AppOrgSlugAccountCommuteTemplatesIdUpdateIndexRoute,
}

const AppOrgSlugRouteRouteWithChildren = AppOrgSlugRouteRoute._addFileChildren(
  AppOrgSlugRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppOrgSlugRouteRoute: typeof AppOrgSlugRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppOrgSlugRouteRoute: AppOrgSlugRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
  LoginErrorIndexRoute: typeof LoginErrorIndexRoute
  LoginVerifyIndexRoute: typeof LoginVerifyIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
  LoginErrorIndexRoute: LoginErrorIndexRoute,
  LoginVerifyIndexRoute: LoginVerifyIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface ManagerOrgSlugRouteRouteChildren {
  ManagerOrgSlugIndexRoute: typeof ManagerOrgSlugIndexRoute
  ManagerOrgSlugAccountIndexRoute: typeof ManagerOrgSlugAccountIndexRoute
  ManagerOrgSlugStatsIndexRoute: typeof ManagerOrgSlugStatsIndexRoute
  ManagerOrgSlugUsersIndexRoute: typeof ManagerOrgSlugUsersIndexRoute
  ManagerOrgSlugUsersIdIndexRoute: typeof ManagerOrgSlugUsersIdIndexRoute
  ManagerOrgSlugUsersNewIndexRoute: typeof ManagerOrgSlugUsersNewIndexRoute
  ManagerOrgSlugUsersIdUpdateIndexRoute: typeof ManagerOrgSlugUsersIdUpdateIndexRoute
}

const ManagerOrgSlugRouteRouteChildren: ManagerOrgSlugRouteRouteChildren = {
  ManagerOrgSlugIndexRoute: ManagerOrgSlugIndexRoute,
  ManagerOrgSlugAccountIndexRoute: ManagerOrgSlugAccountIndexRoute,
  ManagerOrgSlugStatsIndexRoute: ManagerOrgSlugStatsIndexRoute,
  ManagerOrgSlugUsersIndexRoute: ManagerOrgSlugUsersIndexRoute,
  ManagerOrgSlugUsersIdIndexRoute: ManagerOrgSlugUsersIdIndexRoute,
  ManagerOrgSlugUsersNewIndexRoute: ManagerOrgSlugUsersNewIndexRoute,
  ManagerOrgSlugUsersIdUpdateIndexRoute: ManagerOrgSlugUsersIdUpdateIndexRoute,
}

const ManagerOrgSlugRouteRouteWithChildren =
  ManagerOrgSlugRouteRoute._addFileChildren(ManagerOrgSlugRouteRouteChildren)

interface ManagerOrganizationsRouteRouteChildren {
  ManagerOrganizationsIndexRoute: typeof ManagerOrganizationsIndexRoute
  ManagerOrganizationsNewIndexRoute: typeof ManagerOrganizationsNewIndexRoute
}

const ManagerOrganizationsRouteRouteChildren: ManagerOrganizationsRouteRouteChildren =
  {
    ManagerOrganizationsIndexRoute: ManagerOrganizationsIndexRoute,
    ManagerOrganizationsNewIndexRoute: ManagerOrganizationsNewIndexRoute,
  }

const ManagerOrganizationsRouteRouteWithChildren =
  ManagerOrganizationsRouteRoute._addFileChildren(
    ManagerOrganizationsRouteRouteChildren,
  )

interface ManagerUsersRouteRouteChildren {
  ManagerUsersIndexRoute: typeof ManagerUsersIndexRoute
  ManagerUsersIdIndexRoute: typeof ManagerUsersIdIndexRoute
  ManagerUsersNewIndexRoute: typeof ManagerUsersNewIndexRoute
  ManagerUsersIdUpdateIndexRoute: typeof ManagerUsersIdUpdateIndexRoute
}

const ManagerUsersRouteRouteChildren: ManagerUsersRouteRouteChildren = {
  ManagerUsersIndexRoute: ManagerUsersIndexRoute,
  ManagerUsersIdIndexRoute: ManagerUsersIdIndexRoute,
  ManagerUsersNewIndexRoute: ManagerUsersNewIndexRoute,
  ManagerUsersIdUpdateIndexRoute: ManagerUsersIdUpdateIndexRoute,
}

const ManagerUsersRouteRouteWithChildren =
  ManagerUsersRouteRoute._addFileChildren(ManagerUsersRouteRouteChildren)

interface ManagerRouteRouteChildren {
  ManagerOrgSlugRouteRoute: typeof ManagerOrgSlugRouteRouteWithChildren
  ManagerOrganizationsRouteRoute: typeof ManagerOrganizationsRouteRouteWithChildren
  ManagerUsersRouteRoute: typeof ManagerUsersRouteRouteWithChildren
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteRouteChildren: ManagerRouteRouteChildren = {
  ManagerOrgSlugRouteRoute: ManagerOrgSlugRouteRouteWithChildren,
  ManagerOrganizationsRouteRoute: ManagerOrganizationsRouteRouteWithChildren,
  ManagerUsersRouteRoute: ManagerUsersRouteRouteWithChildren,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteRouteWithChildren = ManagerRouteRoute._addFileChildren(
  ManagerRouteRouteChildren,
)

interface ApiOpenapiAppRouteChildren {
  ApiOpenapiAppSchemaRoute: typeof ApiOpenapiAppSchemaRoute
}

const ApiOpenapiAppRouteChildren: ApiOpenapiAppRouteChildren = {
  ApiOpenapiAppSchemaRoute: ApiOpenapiAppSchemaRoute,
}

const ApiOpenapiAppRouteWithChildren = ApiOpenapiAppRoute._addFileChildren(
  ApiOpenapiAppRouteChildren,
)

interface ApiOpenapiAuthRouteChildren {
  ApiOpenapiAuthSchemaRoute: typeof ApiOpenapiAuthSchemaRoute
}

const ApiOpenapiAuthRouteChildren: ApiOpenapiAuthRouteChildren = {
  ApiOpenapiAuthSchemaRoute: ApiOpenapiAuthSchemaRoute,
}

const ApiOpenapiAuthRouteWithChildren = ApiOpenapiAuthRoute._addFileChildren(
  ApiOpenapiAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  ManagerRouteRoute: ManagerRouteRouteWithChildren,
  LogoutRoute: LogoutRoute,
  ApiUploadRoute: ApiUploadRoute,
  InvitationsIdRoute: InvitationsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronDailyReminderRoute: ApiCronDailyReminderRoute,
  ApiOpenapiAppRoute: ApiOpenapiAppRouteWithChildren,
  ApiOpenapiAuthRoute: ApiOpenapiAuthRouteWithChildren,
  ApiRestSplatRoute: ApiRestSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiDevEmailTemplateRoute: ApiDevEmailTemplateRoute,
  ApiDevSlackTemplateRoute: ApiDevSlackTemplateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
