/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ManagerRouteRouteImport } from './routes/manager/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ManagerUsersIndexRouteImport } from './routes/manager/users/index'
import { Route as ManagerDashboardIndexRouteImport } from './routes/manager/dashboard.index'
import { Route as ManagerAccountIndexRouteImport } from './routes/manager/account.index'
import { Route as LoginVerifyIndexRouteImport } from './routes/login/verify.index'
import { Route as LoginErrorIndexRouteImport } from './routes/login/error.index'
import { Route as AppRequestsIndexRouteImport } from './routes/app/requests/index'
import { Route as AppCommutesIndexRouteImport } from './routes/app/commutes/index'
import { Route as AppAccountIndexRouteImport } from './routes/app/account/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiRestSplatRouteImport } from './routes/api/rest.$'
import { Route as ApiOpenapiAuthRouteImport } from './routes/api/openapi/auth'
import { Route as ApiOpenapiAppRouteImport } from './routes/api/openapi/app'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ManagerUsersNewIndexRouteImport } from './routes/manager/users/new.index'
import { Route as ManagerUsersIdIndexRouteImport } from './routes/manager/users/$id.index'
import { Route as AppCommutesNewIndexRouteImport } from './routes/app/commutes/new.index'
import { Route as AppAccountLocationsIndexRouteImport } from './routes/app/account/locations/index'
import { Route as AppAccountCommuteTemplatesIndexRouteImport } from './routes/app/account/commute-templates/index'
import { Route as ApiOpenapiAuthSchemaRouteImport } from './routes/api/openapi/auth.schema'
import { Route as ApiOpenapiAppSchemaRouteImport } from './routes/api/openapi/app.schema'
import { Route as ApiDevEmailTemplateRouteImport } from './routes/api/dev.email.$template'
import { Route as ManagerUsersIdUpdateIndexRouteImport } from './routes/manager/users/$id.update.index'
import { Route as AppAccountLocationsNewIndexRouteImport } from './routes/app/account/locations/new.index'
import { Route as AppAccountCommuteTemplatesNewIndexRouteImport } from './routes/app/account/commute-templates/new.index'
import { Route as AppAccountLocationsIdUpdateIndexRouteImport } from './routes/app/account/locations/$id.update.index'
import { Route as AppAccountCommuteTemplatesIdUpdateIndexRouteImport } from './routes/app/account/commute-templates/$id.update.index'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRouteRoute = ManagerRouteRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerUsersIndexRoute = ManagerUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerDashboardIndexRoute = ManagerDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerAccountIndexRoute = ManagerAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const LoginVerifyIndexRoute = LoginVerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const LoginErrorIndexRoute = LoginErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppRequestsIndexRoute = AppRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommutesIndexRoute = AppCommutesIndexRouteImport.update({
  id: '/commutes/',
  path: '/commutes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestSplatRoute = ApiRestSplatRouteImport.update({
  id: '/api/rest/$',
  path: '/api/rest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiAuthRoute = ApiOpenapiAuthRouteImport.update({
  id: '/api/openapi/auth',
  path: '/api/openapi/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiAppRoute = ApiOpenapiAppRouteImport.update({
  id: '/api/openapi/app',
  path: '/api/openapi/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerUsersNewIndexRoute = ManagerUsersNewIndexRouteImport.update({
  id: '/users/new/',
  path: '/users/new/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerUsersIdIndexRoute = ManagerUsersIdIndexRouteImport.update({
  id: '/users/$id/',
  path: '/users/$id/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const AppCommutesNewIndexRoute = AppCommutesNewIndexRouteImport.update({
  id: '/commutes/new/',
  path: '/commutes/new/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountLocationsIndexRoute =
  AppAccountLocationsIndexRouteImport.update({
    id: '/account/locations/',
    path: '/account/locations/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAccountCommuteTemplatesIndexRoute =
  AppAccountCommuteTemplatesIndexRouteImport.update({
    id: '/account/commute-templates/',
    path: '/account/commute-templates/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApiOpenapiAuthSchemaRoute = ApiOpenapiAuthSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => ApiOpenapiAuthRoute,
} as any)
const ApiOpenapiAppSchemaRoute = ApiOpenapiAppSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => ApiOpenapiAppRoute,
} as any)
const ApiDevEmailTemplateRoute = ApiDevEmailTemplateRouteImport.update({
  id: '/api/dev/email/$template',
  path: '/api/dev/email/$template',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerUsersIdUpdateIndexRoute =
  ManagerUsersIdUpdateIndexRouteImport.update({
    id: '/users/$id/update/',
    path: '/users/$id/update/',
    getParentRoute: () => ManagerRouteRoute,
  } as any)
const AppAccountLocationsNewIndexRoute =
  AppAccountLocationsNewIndexRouteImport.update({
    id: '/account/locations/new/',
    path: '/account/locations/new/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAccountCommuteTemplatesNewIndexRoute =
  AppAccountCommuteTemplatesNewIndexRouteImport.update({
    id: '/account/commute-templates/new/',
    path: '/account/commute-templates/new/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAccountLocationsIdUpdateIndexRoute =
  AppAccountLocationsIdUpdateIndexRouteImport.update({
    id: '/account/locations/$id/update/',
    path: '/account/locations/$id/update/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAccountCommuteTemplatesIdUpdateIndexRoute =
  AppAccountCommuteTemplatesIdUpdateIndexRouteImport.update({
    id: '/account/commute-templates/$id/update/',
    path: '/account/commute-templates/$id/update/',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/api/upload': typeof ApiUploadRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/openapi/app': typeof ApiOpenapiAppRouteWithChildren
  '/api/openapi/auth': typeof ApiOpenapiAuthRouteWithChildren
  '/api/rest/$': typeof ApiRestSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/commutes/': typeof AppCommutesIndexRoute
  '/app/requests/': typeof AppRequestsIndexRoute
  '/login/error/': typeof LoginErrorIndexRoute
  '/login/verify/': typeof LoginVerifyIndexRoute
  '/manager/account/': typeof ManagerAccountIndexRoute
  '/manager/dashboard/': typeof ManagerDashboardIndexRoute
  '/manager/users/': typeof ManagerUsersIndexRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/openapi/app/schema': typeof ApiOpenapiAppSchemaRoute
  '/api/openapi/auth/schema': typeof ApiOpenapiAuthSchemaRoute
  '/app/account/commute-templates/': typeof AppAccountCommuteTemplatesIndexRoute
  '/app/account/locations/': typeof AppAccountLocationsIndexRoute
  '/app/commutes/new/': typeof AppCommutesNewIndexRoute
  '/manager/users/$id/': typeof ManagerUsersIdIndexRoute
  '/manager/users/new/': typeof ManagerUsersNewIndexRoute
  '/app/account/commute-templates/new/': typeof AppAccountCommuteTemplatesNewIndexRoute
  '/app/account/locations/new/': typeof AppAccountLocationsNewIndexRoute
  '/manager/users/$id/update/': typeof ManagerUsersIdUpdateIndexRoute
  '/app/account/commute-templates/$id/update/': typeof AppAccountCommuteTemplatesIdUpdateIndexRoute
  '/app/account/locations/$id/update/': typeof AppAccountLocationsIdUpdateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/api/upload': typeof ApiUploadRoute
  '/app': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/openapi/app': typeof ApiOpenapiAppRouteWithChildren
  '/api/openapi/auth': typeof ApiOpenapiAuthRouteWithChildren
  '/api/rest/$': typeof ApiRestSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/commutes': typeof AppCommutesIndexRoute
  '/app/requests': typeof AppRequestsIndexRoute
  '/login/error': typeof LoginErrorIndexRoute
  '/login/verify': typeof LoginVerifyIndexRoute
  '/manager/account': typeof ManagerAccountIndexRoute
  '/manager/dashboard': typeof ManagerDashboardIndexRoute
  '/manager/users': typeof ManagerUsersIndexRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/openapi/app/schema': typeof ApiOpenapiAppSchemaRoute
  '/api/openapi/auth/schema': typeof ApiOpenapiAuthSchemaRoute
  '/app/account/commute-templates': typeof AppAccountCommuteTemplatesIndexRoute
  '/app/account/locations': typeof AppAccountLocationsIndexRoute
  '/app/commutes/new': typeof AppCommutesNewIndexRoute
  '/manager/users/$id': typeof ManagerUsersIdIndexRoute
  '/manager/users/new': typeof ManagerUsersNewIndexRoute
  '/app/account/commute-templates/new': typeof AppAccountCommuteTemplatesNewIndexRoute
  '/app/account/locations/new': typeof AppAccountLocationsNewIndexRoute
  '/manager/users/$id/update': typeof ManagerUsersIdUpdateIndexRoute
  '/app/account/commute-templates/$id/update': typeof AppAccountCommuteTemplatesIdUpdateIndexRoute
  '/app/account/locations/$id/update': typeof AppAccountLocationsIdUpdateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/api/upload': typeof ApiUploadRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/openapi/app': typeof ApiOpenapiAppRouteWithChildren
  '/api/openapi/auth': typeof ApiOpenapiAuthRouteWithChildren
  '/api/rest/$': typeof ApiRestSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/commutes/': typeof AppCommutesIndexRoute
  '/app/requests/': typeof AppRequestsIndexRoute
  '/login/error/': typeof LoginErrorIndexRoute
  '/login/verify/': typeof LoginVerifyIndexRoute
  '/manager/account/': typeof ManagerAccountIndexRoute
  '/manager/dashboard/': typeof ManagerDashboardIndexRoute
  '/manager/users/': typeof ManagerUsersIndexRoute
  '/api/dev/email/$template': typeof ApiDevEmailTemplateRoute
  '/api/openapi/app/schema': typeof ApiOpenapiAppSchemaRoute
  '/api/openapi/auth/schema': typeof ApiOpenapiAuthSchemaRoute
  '/app/account/commute-templates/': typeof AppAccountCommuteTemplatesIndexRoute
  '/app/account/locations/': typeof AppAccountLocationsIndexRoute
  '/app/commutes/new/': typeof AppCommutesNewIndexRoute
  '/manager/users/$id/': typeof ManagerUsersIdIndexRoute
  '/manager/users/new/': typeof ManagerUsersNewIndexRoute
  '/app/account/commute-templates/new/': typeof AppAccountCommuteTemplatesNewIndexRoute
  '/app/account/locations/new/': typeof AppAccountLocationsNewIndexRoute
  '/manager/users/$id/update/': typeof ManagerUsersIdUpdateIndexRoute
  '/app/account/commute-templates/$id/update/': typeof AppAccountCommuteTemplatesIdUpdateIndexRoute
  '/app/account/locations/$id/update/': typeof AppAccountLocationsIdUpdateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/manager'
    | '/logout'
    | '/api/upload'
    | '/app/'
    | '/login/'
    | '/manager/'
    | '/api/auth/$'
    | '/api/openapi/app'
    | '/api/openapi/auth'
    | '/api/rest/$'
    | '/api/rpc/$'
    | '/app/account/'
    | '/app/commutes/'
    | '/app/requests/'
    | '/login/error/'
    | '/login/verify/'
    | '/manager/account/'
    | '/manager/dashboard/'
    | '/manager/users/'
    | '/api/dev/email/$template'
    | '/api/openapi/app/schema'
    | '/api/openapi/auth/schema'
    | '/app/account/commute-templates/'
    | '/app/account/locations/'
    | '/app/commutes/new/'
    | '/manager/users/$id/'
    | '/manager/users/new/'
    | '/app/account/commute-templates/new/'
    | '/app/account/locations/new/'
    | '/manager/users/$id/update/'
    | '/app/account/commute-templates/$id/update/'
    | '/app/account/locations/$id/update/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/api/upload'
    | '/app'
    | '/login'
    | '/manager'
    | '/api/auth/$'
    | '/api/openapi/app'
    | '/api/openapi/auth'
    | '/api/rest/$'
    | '/api/rpc/$'
    | '/app/account'
    | '/app/commutes'
    | '/app/requests'
    | '/login/error'
    | '/login/verify'
    | '/manager/account'
    | '/manager/dashboard'
    | '/manager/users'
    | '/api/dev/email/$template'
    | '/api/openapi/app/schema'
    | '/api/openapi/auth/schema'
    | '/app/account/commute-templates'
    | '/app/account/locations'
    | '/app/commutes/new'
    | '/manager/users/$id'
    | '/manager/users/new'
    | '/app/account/commute-templates/new'
    | '/app/account/locations/new'
    | '/manager/users/$id/update'
    | '/app/account/commute-templates/$id/update'
    | '/app/account/locations/$id/update'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/manager'
    | '/logout'
    | '/api/upload'
    | '/app/'
    | '/login/'
    | '/manager/'
    | '/api/auth/$'
    | '/api/openapi/app'
    | '/api/openapi/auth'
    | '/api/rest/$'
    | '/api/rpc/$'
    | '/app/account/'
    | '/app/commutes/'
    | '/app/requests/'
    | '/login/error/'
    | '/login/verify/'
    | '/manager/account/'
    | '/manager/dashboard/'
    | '/manager/users/'
    | '/api/dev/email/$template'
    | '/api/openapi/app/schema'
    | '/api/openapi/auth/schema'
    | '/app/account/commute-templates/'
    | '/app/account/locations/'
    | '/app/commutes/new/'
    | '/manager/users/$id/'
    | '/manager/users/new/'
    | '/app/account/commute-templates/new/'
    | '/app/account/locations/new/'
    | '/manager/users/$id/update/'
    | '/app/account/commute-templates/$id/update/'
    | '/app/account/locations/$id/update/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  ManagerRouteRoute: typeof ManagerRouteRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOpenapiAppRoute: typeof ApiOpenapiAppRouteWithChildren
  ApiOpenapiAuthRoute: typeof ApiOpenapiAuthRouteWithChildren
  ApiRestSplatRoute: typeof ApiRestSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiDevEmailTemplateRoute: typeof ApiDevEmailTemplateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/users/': {
      id: '/manager/users/'
      path: '/users'
      fullPath: '/manager/users/'
      preLoaderRoute: typeof ManagerUsersIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/dashboard/': {
      id: '/manager/dashboard/'
      path: '/dashboard'
      fullPath: '/manager/dashboard/'
      preLoaderRoute: typeof ManagerDashboardIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/account/': {
      id: '/manager/account/'
      path: '/account'
      fullPath: '/manager/account/'
      preLoaderRoute: typeof ManagerAccountIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/login/verify/': {
      id: '/login/verify/'
      path: '/verify'
      fullPath: '/login/verify/'
      preLoaderRoute: typeof LoginVerifyIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/login/error/': {
      id: '/login/error/'
      path: '/error'
      fullPath: '/login/error/'
      preLoaderRoute: typeof LoginErrorIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/app/requests/': {
      id: '/app/requests/'
      path: '/requests'
      fullPath: '/app/requests/'
      preLoaderRoute: typeof AppRequestsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/commutes/': {
      id: '/app/commutes/'
      path: '/commutes'
      fullPath: '/app/commutes/'
      preLoaderRoute: typeof AppCommutesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/account'
      fullPath: '/app/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rest/$': {
      id: '/api/rest/$'
      path: '/api/rest/$'
      fullPath: '/api/rest/$'
      preLoaderRoute: typeof ApiRestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/auth': {
      id: '/api/openapi/auth'
      path: '/api/openapi/auth'
      fullPath: '/api/openapi/auth'
      preLoaderRoute: typeof ApiOpenapiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/app': {
      id: '/api/openapi/app'
      path: '/api/openapi/app'
      fullPath: '/api/openapi/app'
      preLoaderRoute: typeof ApiOpenapiAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/users/new/': {
      id: '/manager/users/new/'
      path: '/users/new'
      fullPath: '/manager/users/new/'
      preLoaderRoute: typeof ManagerUsersNewIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/users/$id/': {
      id: '/manager/users/$id/'
      path: '/users/$id'
      fullPath: '/manager/users/$id/'
      preLoaderRoute: typeof ManagerUsersIdIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/app/commutes/new/': {
      id: '/app/commutes/new/'
      path: '/commutes/new'
      fullPath: '/app/commutes/new/'
      preLoaderRoute: typeof AppCommutesNewIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account/locations/': {
      id: '/app/account/locations/'
      path: '/account/locations'
      fullPath: '/app/account/locations/'
      preLoaderRoute: typeof AppAccountLocationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account/commute-templates/': {
      id: '/app/account/commute-templates/'
      path: '/account/commute-templates'
      fullPath: '/app/account/commute-templates/'
      preLoaderRoute: typeof AppAccountCommuteTemplatesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/openapi/auth/schema': {
      id: '/api/openapi/auth/schema'
      path: '/schema'
      fullPath: '/api/openapi/auth/schema'
      preLoaderRoute: typeof ApiOpenapiAuthSchemaRouteImport
      parentRoute: typeof ApiOpenapiAuthRoute
    }
    '/api/openapi/app/schema': {
      id: '/api/openapi/app/schema'
      path: '/schema'
      fullPath: '/api/openapi/app/schema'
      preLoaderRoute: typeof ApiOpenapiAppSchemaRouteImport
      parentRoute: typeof ApiOpenapiAppRoute
    }
    '/api/dev/email/$template': {
      id: '/api/dev/email/$template'
      path: '/api/dev/email/$template'
      fullPath: '/api/dev/email/$template'
      preLoaderRoute: typeof ApiDevEmailTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/users/$id/update/': {
      id: '/manager/users/$id/update/'
      path: '/users/$id/update'
      fullPath: '/manager/users/$id/update/'
      preLoaderRoute: typeof ManagerUsersIdUpdateIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/app/account/locations/new/': {
      id: '/app/account/locations/new/'
      path: '/account/locations/new'
      fullPath: '/app/account/locations/new/'
      preLoaderRoute: typeof AppAccountLocationsNewIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account/commute-templates/new/': {
      id: '/app/account/commute-templates/new/'
      path: '/account/commute-templates/new'
      fullPath: '/app/account/commute-templates/new/'
      preLoaderRoute: typeof AppAccountCommuteTemplatesNewIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account/locations/$id/update/': {
      id: '/app/account/locations/$id/update/'
      path: '/account/locations/$id/update'
      fullPath: '/app/account/locations/$id/update/'
      preLoaderRoute: typeof AppAccountLocationsIdUpdateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account/commute-templates/$id/update/': {
      id: '/app/account/commute-templates/$id/update/'
      path: '/account/commute-templates/$id/update'
      fullPath: '/app/account/commute-templates/$id/update/'
      preLoaderRoute: typeof AppAccountCommuteTemplatesIdUpdateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppCommutesIndexRoute: typeof AppCommutesIndexRoute
  AppRequestsIndexRoute: typeof AppRequestsIndexRoute
  AppAccountCommuteTemplatesIndexRoute: typeof AppAccountCommuteTemplatesIndexRoute
  AppAccountLocationsIndexRoute: typeof AppAccountLocationsIndexRoute
  AppCommutesNewIndexRoute: typeof AppCommutesNewIndexRoute
  AppAccountCommuteTemplatesNewIndexRoute: typeof AppAccountCommuteTemplatesNewIndexRoute
  AppAccountLocationsNewIndexRoute: typeof AppAccountLocationsNewIndexRoute
  AppAccountCommuteTemplatesIdUpdateIndexRoute: typeof AppAccountCommuteTemplatesIdUpdateIndexRoute
  AppAccountLocationsIdUpdateIndexRoute: typeof AppAccountLocationsIdUpdateIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppCommutesIndexRoute: AppCommutesIndexRoute,
  AppRequestsIndexRoute: AppRequestsIndexRoute,
  AppAccountCommuteTemplatesIndexRoute: AppAccountCommuteTemplatesIndexRoute,
  AppAccountLocationsIndexRoute: AppAccountLocationsIndexRoute,
  AppCommutesNewIndexRoute: AppCommutesNewIndexRoute,
  AppAccountCommuteTemplatesNewIndexRoute:
    AppAccountCommuteTemplatesNewIndexRoute,
  AppAccountLocationsNewIndexRoute: AppAccountLocationsNewIndexRoute,
  AppAccountCommuteTemplatesIdUpdateIndexRoute:
    AppAccountCommuteTemplatesIdUpdateIndexRoute,
  AppAccountLocationsIdUpdateIndexRoute: AppAccountLocationsIdUpdateIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
  LoginErrorIndexRoute: typeof LoginErrorIndexRoute
  LoginVerifyIndexRoute: typeof LoginVerifyIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
  LoginErrorIndexRoute: LoginErrorIndexRoute,
  LoginVerifyIndexRoute: LoginVerifyIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface ManagerRouteRouteChildren {
  ManagerIndexRoute: typeof ManagerIndexRoute
  ManagerAccountIndexRoute: typeof ManagerAccountIndexRoute
  ManagerDashboardIndexRoute: typeof ManagerDashboardIndexRoute
  ManagerUsersIndexRoute: typeof ManagerUsersIndexRoute
  ManagerUsersIdIndexRoute: typeof ManagerUsersIdIndexRoute
  ManagerUsersNewIndexRoute: typeof ManagerUsersNewIndexRoute
  ManagerUsersIdUpdateIndexRoute: typeof ManagerUsersIdUpdateIndexRoute
}

const ManagerRouteRouteChildren: ManagerRouteRouteChildren = {
  ManagerIndexRoute: ManagerIndexRoute,
  ManagerAccountIndexRoute: ManagerAccountIndexRoute,
  ManagerDashboardIndexRoute: ManagerDashboardIndexRoute,
  ManagerUsersIndexRoute: ManagerUsersIndexRoute,
  ManagerUsersIdIndexRoute: ManagerUsersIdIndexRoute,
  ManagerUsersNewIndexRoute: ManagerUsersNewIndexRoute,
  ManagerUsersIdUpdateIndexRoute: ManagerUsersIdUpdateIndexRoute,
}

const ManagerRouteRouteWithChildren = ManagerRouteRoute._addFileChildren(
  ManagerRouteRouteChildren,
)

interface ApiOpenapiAppRouteChildren {
  ApiOpenapiAppSchemaRoute: typeof ApiOpenapiAppSchemaRoute
}

const ApiOpenapiAppRouteChildren: ApiOpenapiAppRouteChildren = {
  ApiOpenapiAppSchemaRoute: ApiOpenapiAppSchemaRoute,
}

const ApiOpenapiAppRouteWithChildren = ApiOpenapiAppRoute._addFileChildren(
  ApiOpenapiAppRouteChildren,
)

interface ApiOpenapiAuthRouteChildren {
  ApiOpenapiAuthSchemaRoute: typeof ApiOpenapiAuthSchemaRoute
}

const ApiOpenapiAuthRouteChildren: ApiOpenapiAuthRouteChildren = {
  ApiOpenapiAuthSchemaRoute: ApiOpenapiAuthSchemaRoute,
}

const ApiOpenapiAuthRouteWithChildren = ApiOpenapiAuthRoute._addFileChildren(
  ApiOpenapiAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  ManagerRouteRoute: ManagerRouteRouteWithChildren,
  LogoutRoute: LogoutRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOpenapiAppRoute: ApiOpenapiAppRouteWithChildren,
  ApiOpenapiAuthRoute: ApiOpenapiAuthRouteWithChildren,
  ApiRestSplatRoute: ApiRestSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiDevEmailTemplateRoute: ApiDevEmailTemplateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
